#!/bin/bash

php bin/console doctrine:database:drop --force >> /dev/null;
rm -r migrations >> /dev/null;
rm -r public/uploads >> /dev/null;

php bin/console doctrine:database:create >> /dev/null;
mkdir migrations
php bin/console make:migration >> /dev/null;
php bin/console doctrine:migrations:migrate --no-interaction >> /dev/null;
php bin/console doctrine:fixtures:load --no-interaction